---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: mac-blue
# description will be included in the image's metadata
description: MacBookPro11,4 that hopefully works

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin
image-version: stable # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: script
    scripts:
      - 1password.sh

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://negativo17.org/repos/fedora-multimedia.repo
    install:
      - mbpfan
      - igt-gpu-tools
      - libva
      - libva-utils
      - intel-vaapi-driver # The i965 driver from negativo17
      - gstreamer1-plugin-vaapi
      - mesa-va-drivers
      - mesa-dri-drivers
      - mesa-libEGL
      - mesa-libGL
      - mesa-libgbm
      - mesa-libglapi
      - ffmpeg
      - libavcodec
      - yt-dlp
      - mpv
      - tuned-utils

    remove:
      #  it is for newer Intel GPUs (Broadwell/Gen8 and up), while we rock HD Graphics 4600 which needs older i965 driver
      # https://fedoraproject.org/wiki/Firefox_Hardware_acceleration#Configure_VA-API_Video_decoding_on_Intel
      - libva-intel-media-driver # Remove iHD driver
      - mesa-vulkan-drivers # No Vulkan support for my GPU
      - intel-mediasdk # Not needed for Haswell
      - intel-vpl-gpu-rt # Not needed for Haswell
      - intel-gmmlib # Only needed by media-driver

  # - type: default-flatpaks
  #   notify: true # Send notification after install/uninstall is finished (true/false)
  #   system:
  #     # If no repo information is specified, Flathub will be used by default
  #     install:
  #       - org.mozilla.firefox
  #       - org.gnome.Loupe
  #     remove:
  #       - org.gnome.eog
  #   user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: systemd
    system:
      enabled:
        - mbpfan.service
