---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: mac-blue
# description will be included in the image's metadata
description: MacBookPro11,4 that hopefully works

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin
image-version: stable # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    # repos:
    # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - mbpfan
      - igt-gpu-tools
      - libva-utils
      - libva-intel-driver
      - yt-dlp
      - mpv
      - ffmpeg-free
      - libavcodec-freeworld

    remove:
      #  it is for newer Intel GPUs (Broadwell/Gen8 and up), while we rock HD Graphics 4600 which needs older i965 driver
      # https://fedoraproject.org/wiki/Firefox_Hardware_acceleration#Configure_VA-API_Video_decoding_on_Intel
      - libva-intel-media-driver
      - mesa-vulkan-drivers # Vulkan on this generation of graphic chip is incomplete at best. 1.0 might work?

  # - type: default-flatpaks
  #   notify: true # Send notification after install/uninstall is finished (true/false)
  #   system:
  #     # If no repo information is specified, Flathub will be used by default
  #     install:
  #       - org.mozilla.firefox
  #       - org.gnome.Loupe
  #     remove:
  #       - org.gnome.eog
  #   user: {} # Also add Flathub user repo, but no user packages

  - type: script
    snippets:
      - for i in /etc/yum.repos.d/rpmfusion-*; do sed -i 's@enabled=1@enabled=0@g' "$i"; done
    scripts:
      - 1password.sh

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: systemd
    system:
      enabled:
        - mbpfan.service
